### ISSUE TITLE
How to read from stream using OpenCV

### ISSUE THREAD

**Issue by Antoniossss** [mesutpiskin/opencv-livestream-over-http#1]
I want the other way around - I want to read network stream. I have no clue how to read video directly from (any) input stream. Do you know how to do it?

**Comment by mesutpiskin** [comment]
Yes, you can video capture properties. 

- https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html
- https://docs.opencv.org/3.4/javadoc/org/opencv/videoio/VideoCapture.html

**Comment by Antoniossss** [comment]
This does not show how to use input stream. Py example shows how to init and capture fro built in camera (or any other camera device) while I need to capture network stream (input stream in general). URL variant does not work as my feed is not available directly via url
