### ISSUE TITLE
Can you explain this code?

### ISSUE THREAD

**Issue by ghost** [mesutpiskin/opencv-livestream-over-http#10]
I can't understand this codes.

    stream.write(("HTTP/1.0 200 OK\r\n" +
                "Connection: close\r\n" +
                "Max-Age: 0\r\n" +
                "Expires: 0\r\n" +
                "Cache-Control: no-store, no-cache, must-revalidate, pre-check=0, post-check=0, max-age=0\r\n" +
                "Pragma: no-cache\r\n" +
                "Content-Type: multipart/x-mixed-replace; " +
                "boundary=" + boundary + "\r\n" +
                "\r\n" +
                "--" + boundary + "\r\n").getBytes());
        }

And this 

https://github.com/mesutpiskin/opencv-live-video-stream-over-http/blob/master/src/main/java/HttpStreamServer.java#L59

Can you explain this?

**Comment by ghost** [comment]
I also have this same doubt.

**Comment by mesutpiskin** [comment]
this is HTTP parameters, HTTP headers let the client and the server pass additional information with an HTTP request or response.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
