### ISSUE TITLE
Can you give a tutorial for opencv-live-video-stream-over-http?

### ISSUE THREAD

**Issue by ghost** [mesutpiskin/opencv-livestream-over-http#2]
Can you give a tutorial for opencv-live-video-stream-over-http?

Because , I did not know to run this project.

help me !!!

**Comment by mesutpiskin** [comment]
Of course, I will update the read me document

**Comment by ghost** [comment]
Help!!!

**Comment by PradeepSimba** [comment]
I want to take a screen shot and stream over http.

it is possible with this project.

**Comment by poorvajappja** [comment]
Give a tutorial.

**Comment by mesutpiskin** [comment]
1) Update your opencv dll reference as readme file.
2) You can open this project with an any java IDE (IntelliJ IDEA, NetBeans or Eclipse, etc.)
3) Run this OpenCVCameraStream.java

**Comment by PradeepSimba** [comment]
I done this . 

![1](https://user-images.githubusercontent.com/45443554/83323761-82aa4f80-a27e-11ea-82fd-df833db2e606.PNG)

But , The browser loading the page for a long time.

I run this project for more than 10 minites . But , the browser contineously loading the web page .

**Comment by ghost** [comment]
How to increase the size of the webcam view ?

**Comment by mesutpiskin** [comment]
@PradeepSimba PradeepSimba The browser loading the page for a long time because streaming continues all the time.

If you want a resize an image then should use the video capture options. 
Ex:
```
VideoCapture videoDevice = new VideoCapture(0);
videoDevice.set(propId, value);
```
for size
`videoDevice.set(Videoio.CV_CAP_PROP_FRAME_WIDTH, 1024);`

or resizer
```
Mat src  =  imread("imageName.jpg");
Mat resizeimage = new Mat();
Size scaleSize = new Size(300,200);
resize(src, resizeimage, scaleSize , 0, 0, INTER_AREA);
```

**Comment by PradeepSimba** [comment]
I want to resize the image with this code 

`Mat src  =  imread("imageName.jpg");
Mat resizeimage = new Mat();
Size scaleSize = new Size(300,200);
resize(src, resizeimage, scaleSize , 0, 0, INTER_AREA);`

But , When I run this code an error occurs.



`
  import org.opencv.core.*;
  import org.opencv.videoio.VideoCapture;
  import javax.swing.*;
  import java.awt.event.ActionEvent;
  import java.awt.event.ActionListener;

  import static org.opencv.imgcodecs.Imgcodecs.imread;
   import static org.opencv.imgproc.Imgproc.INTER_AREA;
   import static org.opencv.imgproc.Imgproc.resize;

   public class OpenCVCameraStream {


    //region Properties
    public static Mat frame = null;
    private static HttpStreamServer httpStreamService;
    static VideoCapture videoCapture;
    static Timer tmrVideoProcess;
    //endregion

    //region Methods

    public static void start() {


        videoCapture = new VideoCapture();
        videoCapture.open(0);
        if (!videoCapture.isOpened()) {
            return;
        }

        frame = new Mat();
        httpStreamService = new HttpStreamServer(frame);
        new Thread(httpStreamService).start();

        tmrVideoProcess = new Timer(100, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (!videoCapture.read(frame)) {
                    tmrVideoProcess.stop();
                }

                //procesed image
                httpStreamService.imag = frame;
                Mat src  =  imread("imageName.jpg");
                Mat resizeimage = new Mat();
                Size scaleSize = new Size(300,200);
                resize(src, resizeimage, scaleSize , 0, 0, INTER_AREA);


            }
        });
        tmrVideoProcess.start();
    }

    public static void main(String[] args) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);//Load opencv native library
        start();
    }

    //endregion}

`


Error ;

`C:\Users\prade\.jdks\openjdk-14\bin\java.exe "-Djava.library.path=D:\install\open cv 3.1\opencv\build\java\x64;D:\install\open cv 3.1\opencv\build\java\x86" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\lib\idea_rt.jar=53064:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\bin" -Dfile.encoding=UTF-8 -classpath "D:\Github\opencv-live-video-stream-over-http\out\production\opencv-live-video-stream-over-http;D:\install\open cv 3.1\opencv\build\java\opencv-310.jar" OpenCVCameraStream
go to  http://localhost:8080 with browserOpenCV Error: Assertion failed (ssize.area() > 0) in cv::resize, file C:\builds\master_PackSlaveAddon-win64-vc12-static\opencv\modules\imgproc\src\imgwarp.cpp, line 3229
Exception in thread "AWT-EventQueue-0" CvException [org.opencv.core.CvException: cv::Exception: C:\builds\master_PackSlaveAddon-win64-vc12-static\opencv\modules\imgproc\src\imgwarp.cpp:3229: error: (-215) ssize.area() > 0 in function cv::resize
]
	at org.opencv.imgproc.Imgproc.resize_0(Native Method)
	at org.opencv.imgproc.Imgproc.resize(Imgproc.java:2707)
	at OpenCVCameraStream$1.actionPerformed(OpenCVCameraStream.java:46)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Process finished with exit code -1`

**Comment by mesutpiskin** [comment]
Omg, really "imageName.jpg", imageName.jpg your file image patg

...
      if (!videoCapture.read(frame)) {
                    tmrVideoProcess.stop();
                }
                //procesed image
               //Pls resize frame object, frame is your mat image
                httpStreamService.imag = frame;
...

**Comment by ghost** [comment]
I done this . But , an error occurs .

`import org.opencv.core.*;
import org.opencv.videoio.VideoCapture;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import static org.opencv.imgcodecs.Imgcodecs.imread;
import static org.opencv.imgproc.Imgproc.INTER_AREA;
import static org.opencv.imgproc.Imgproc.resize;

public class OpenCVCameraStream {

    //region Properties
    public static Mat frame = null;
    private static HttpStreamServer httpStreamService;
    static VideoCapture videoCapture;
    static Timer tmrVideoProcess;
    //endregion

    //region Methods

    public static void start() {


        videoCapture = new VideoCapture();
        videoCapture.open(0);
        if (!videoCapture.isOpened()) {
            return;
        }

        frame = new Mat();
        httpStreamService = new HttpStreamServer(frame);
        new Thread(httpStreamService).start();

        tmrVideoProcess = new Timer(100, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (!videoCapture.read(frame)) {
                    tmrVideoProcess.stop();
                }

                //procesed image
                Mat src  = frame ;
                Mat resizeimage = new Mat();
                Size scaleSize = new Size(500,500);
                resize(src, resizeimage, scaleSize , 0, 0, INTER_AREA);
                httpStreamService.imag = frame;



            }
        });
        tmrVideoProcess.start();
    }

    public static void main(String[] args) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);//Load opencv native library
        start();
    }

    //endregion

}
`


Error :
`C:\Users\prade\.jdks\openjdk-14\bin\java.exe "-Djava.library.path=D:\install\open cv 3.1\opencv\build\java\x64;D:\install\open cv 3.1\opencv\build\java\x86" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\lib\idea_rt.jar=53901:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\bin" -Dfile.encoding=UTF-8 -classpath "D:\Github\opencv-live-video-stream-over-http\out\production\opencv-live-video-stream-over-http;D:\install\open cv 3.1\opencv\build\java\opencv-310.jar" OpenCVCameraStream
go to  http://localhost:8080 with browserOpenCV Error: Unknown error code -10 (Raw image encoder error: Empty JPEG image (DNL not supported)) in cv::BaseImageEncoder::throwOnEror, file C:\builds\master_PackSlaveAddon-win64-vc12-static\opencv\modules\imgcodecs\src\grfmt_base.cpp, line 139
OpenCV Error: Unknown error code -10 (Raw image encoder error: Empty JPEG image (DNL not supported)) in cv::BaseImageEncoder::throwOnEror, file C:\builds\master_PackSlaveAddon-win64-vc12-static\opencv\modules\imgcodecs\src\grfmt_base.cpp, line 139
`
