### ISSUE TITLE
How to run this project ? 

### ISSUE THREAD

**Issue by ghost** [mesutpiskin/opencv-livestream-over-http#3]
Give a sample project.

**Comment by mesutpiskin** [comment]
This is sample project.
You can open this project with an any java IDE (IntelliJ IDEA, NetBeans or Eclipse, etc.) and run this `OpenCVCameraStream.java`

**Comment by ghost** [comment]
How to set the webcam view fit to web page ?

**Comment by mesutpiskin** [comment]
Dublicated https://github.com/mesutpiskin/opencv-live-video-stream-over-http/issues/2
