### ISSUE TITLE
How to use web  cam with this project ?

### ISSUE THREAD

**Issue by ashokkumarvel** [mesutpiskin/opencv-livestream-over-http#4]
I want to stream web cam with opencv over http.

 I did not know to run this project.

I want to use webcam sarxos https://github.com/sarxos/webcam-capture  library with this project.

So , how can I done it with this project?

Add a sample project.

**Comment by mesutpiskin** [comment]
This is sample project, video capture 0 is your default webcam. https://docs.opencv.org/3.4/javadoc/org/opencv/videoio/VideoCapture.html
```
videoCapture = new VideoCapture();
videoCapture.open(0);
```

https://github.com/mesutpiskin/opencv-live-video-stream-over-http/blob/master/src/main/java/OpenCVCameraStream.java

**Comment by ashokkumarvel** [comment]
I want to sent bufferedimage .

How  to sent bufferedimage ?

**Comment by ghost** [comment]
I also have this doubt.

Can you give an answer?

**Comment by mesutpiskin** [comment]
@ashokkumarvel i don't know what to say, sory.

**Comment by ashokkumarvel** [comment]
How to convert the bufferedimage to mat and stream it over http ?
