### ISSUE TITLE
How to add native library for linux ?

### ISSUE THREAD

**Issue by ghost** [mesutpiskin/opencv-livestream-over-http#8]
I added the opencv's native library for windows.

but, how can I add the opencv's native library for both linux 32 bit and 64 bit?

![Screenshot_20200626-201013_Edge](https://user-images.githubusercontent.com/45443554/85869459-53d5b980-b7e9-11ea-9d2d-daadc31f30f2.jpg)

In opencv release page there is no downloading option for linux. Then , How can I add the native library ?

where to download the opencv's native library for linux ?

Help me!!!

**Comment by mesutpiskin** [comment]
You can do this

   `System.loadLibrary("yournativelibrarypath.so");`

**Comment by ghost** [comment]
![20200629_072113](https://user-images.githubusercontent.com/45443554/85965275-c6a58700-b9d9-11ea-9b34-a139c5ce944b.jpg)


I downloaded opencv for windows.

But , where I can find the .so file for linux ?

**Comment by mesutpiskin** [comment]
You need to build a opencv source code for so files.
How to build opencv
https://docs.opencv.org/4.3.0/d7/d9f/tutorial_linux_install.html

or my tutorial for linux building (Turkish language only, maybe you can translate)
http://mesutpiskin.com/blog/linux-isletim-sistemi-icin-opencv-kurulumu.html

**Comment by ghost** [comment]
Can I follow this tutorial ?

http://mesutpiskin.com/blog/linux-isletim-sistemi-icin-opencv-kurulumu.html

https://youtu.be/JYexxS7Pwrw

I am using Ubuntu os . if I create a .so file with ubuntu .   will it work on other linux   os like kali linux , debain , and etc...,?

will it work on both 32 bit and 64 bit?

**Comment by ghost** [comment]
Help !!!

https://github.com/mesutpiskin/opencv-live-video-stream-over-http/issues/8#issuecomment-651040045

**Comment by ghost** [comment]
I am using Ubuntu os . if I create a .so file with ubuntu . will it work on other linux os like kali linux , debain , linux 
mint  , fedora centos ,  Arch linux , manjaro , openSUSE  and etc...,?

**Comment by mesutpiskin** [comment]
I think it will work in the debian family

**Comment by ghost** [comment]
I want to make a jar with this project for all linux os.

Is it possible with this project?

Give more information. 

Help!!!

**Comment by mesutpiskin** [comment]
i don't know, you can try it.
