### ISSUE TITLE
How can I access this in multiple tabs in browser?

### ISSUE THREAD

**Issue by ghost** [mesutpiskin/opencv-livestream-over-http#9]
When I open this page in two tabs it  worked in one tab.

How can I access this in multiple tabs in browser?

**Comment by mesutpiskin** [comment]
I think you need to open multiple server socket connections. I do not know this, you can look at the java server sockets documents.

**Comment by ghost** [comment]
How to open multiple server socket  connections?

I searched on internet for this.

But , I can't solve this.

Can you give more information?

**Comment by mesutpiskin** [comment]
A new tab opens a new socket connection, I don't know how to fix this.
Maybe use other http server application, jetty, undertow, etc.

**Comment by isaric** [comment]
Hi @mesutpiskin , first let me say many thanks for your example. It helped me greately in my own development. 
@poorvajappja I solved the problem that you are having by developing the server in spring boot using a StreamingResponseBody but I based all the other things on @mesutpiskin example. Each new session opens it's own VideoCapture so they can receive the video. I will upload a demo project to github soon.

**Comment by mesutpiskin** [comment]
I'm happy for you, that's great. If you share your project, can you add a link here too?

**Comment by isaric** [comment]
In the end the solution is a little bit different than I described originally. You can see for yourself. Here is the [link](https://github.com/isaric/stream-demo)

**Comment by tom131313** [comment]
@mesutpiskin Thanks for this project.  Well done!  It's just what I needed for a simple server of a camera frame with an overlay of an OpenCV drawing.  My after-school robotics students can use this to continue learning since they can't get to the robot during the lengthy lockdown.  We feed the HTTP image to GRIP (WPIRoboticsProjects in GitHub) to adjust settings then put them in the OpenCV code on the robot.

I wanted to control the JPG quality so I gleaned this technique from StackOverflow answers.  You could add another method and call it pushImageCompressed if you want to.
```java
    public void pushImage(Mat frame) throws IOException {
            // control JPG compress without saving
            float qualityJPG = 1.f; // 0. to 1.; 0 most compressed; 1 least compressed
            if (frame == null)
            return;
        try {

            BufferedImage img = Mat2bufferedImage(frame);
                
            // Create in-memory stream
            ByteArrayOutputStream compressed = new ByteArrayOutputStream();

            //ImageOutputStream outputStreamJPG = ImageIO.createImageOutputStream(compressed); // default disk buffer
            ImageOutputStream outputStreamJPG = new MemoryCacheImageOutputStream(compressed); // in memory
            
            // Obtain writer for JPEG format
            ImageWriter jpgWriter = ImageIO.getImageWritersByFormatName("jpg").next();
            
            // Configure JPEG compression/quality
            ImageWriteParam jpgWriteParam = jpgWriter.getDefaultWriteParam();
            jpgWriteParam.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
            jpgWriteParam.setCompressionQuality(qualityJPG);
            
            // Set your in-memory stream as the output
            jpgWriter.setOutput(outputStreamJPG);

            // Write image as JPEG w/configured settings to the in-memory stream            
            IIOImage outputImage = new IIOImage(img, null, null);
            jpgWriter.write(null, outputImage, jpgWriteParam);
            
            // Dispose the writer to free resources
            jpgWriter.dispose();

            // Get compressed data to write it
            byte[] imageBytes = compressed.toByteArray();
        
            outputStream = socket.getOutputStream();

            outputStream.write(("Content-type: image/jpeg\r\n" +
                    "Content-Length: " + imageBytes.length + "\r\n" +
                    "\r\n").getBytes());

            outputStream.write(imageBytes);

            outputStream.write(("\r\n--" + boundary + "\r\n").getBytes());
 
        } catch (Exception ex) {
            ex.printStackTrace();
            socket = serverSocket.accept();
            writeHeader(socket.getOutputStream(), boundary);
        }
    }
```

**Comment by tom131313** [comment]
@poorvajappja I converted this single-use server to multi-clients and it's [here](https://github.com/tom131313/opencv-live-video-stream-over-http).  I'm sure it's not "industrial strength" but it seems to work.  I was happy with the single-use here but since you mentioned it, I practiced multi-threading and socket programming to learn.  It's still pure Java and OpenCV - no additional libraries required which is why I liked this one.

**Comment by ghost** [comment]
@tom131313  it worked. thank you very much.

**Comment by ghost** [comment]
@mesutpiskin  @tom131313 

I want to send the String contineously over http socket.


      
       ac  f=new ac();
      String string = f.getSt();

      byte[] byteArray = string.getBytes();

      os.write("HTTP/1.0 200 OK\n".getBytes());
      os.write(new String("Content-Length: " + byteArray.length + "\n").getBytes());
      os.write("Content-Type: text/html\n\n".getBytes());

      os.write(byteArray);




I want to get  and send the the String over the socket contineously .



This project get and sent the webcam image over http socket contineously.

But, I want to get  and send the the String over the socket contineously .

How can I do this ?

I asked this question because I did't know more about http stream  in java.

and I can't understand the following codes 

       stream.write(("HTTP/1.0 200 OK\r\n" +
                "Connection: close\r\n" +
                "Max-Age: 0\r\n" +
                "Expires: 0\r\n" +
                "Cache-Control: no-store, no-cache, must-revalidate, pre-check=0, post-check=0, max-age=0\r\n" +
                "Pragma: no-cache\r\n" +
                "Content-Type: multipart/x-mixed-replace; " +
                "boundary=" + boundary + "\r\n" +
                "\r\n" +
                "--" + boundary + "\r\n").getBytes());


and this


    outputStream.write(("Content-type: image/jpeg\r\n" +
                    "Content-Length: " + imageBytes.length + "\r\n" +
                    "\r\n").getBytes());
